apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: fdp-nqzkb-worker
  namespace: openshift-machine-api
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: fdp-nqzkb-worker-0
