apiVersion: v1
kind: Pod
metadata:
  name: testpmd-host-device
  namespace: example-cnf
  annotations:
    k8s.v1.cni.cncf.io/networks: vhost1
spec:
  containers:
  - name: testpmd
    command: ["sleep", "99999"]
    image: registry.redhat.io/openshift4/dpdk-base-rhel8:v4.6
    resources:
      requests:
        memory: 1000Mi
        hugepages-1Gi: 3Gi
        cpu: '1'
      limits:
        hugepages-1Gi: 3Gi
        cpu: '1'
        memory: 1000Mi
    volumeMounts:
      - mountPath: /dev/hugepages
        name: hugepage
        readOnly: False
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
