apiVersion: v1
kind: Pod
metadata:
  name: cni-plugin-manual
  namespace: openshift-multus
spec:
  containers:
  - command:
    - /entrypoint/cnibincopy.sh
    env:
    - name: RHEL7_SOURCE_DIRECTORY
      value: /usr/src/plugins/rhel7/bin/
    - name: RHEL8_SOURCE_DIRECTORY
      value: /usr/src/plugins/rhel8/bin/
    - name: DEFAULT_SOURCE_DIRECTORY
      value: /usr/src/plugins/bin/
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fbd0a11155a23a219ed9dc82503f730645f71e593f5d44fb83eaa052ce5ceb43
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    name: cni-plugins
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /entrypoint
      name: cni-binary-copy
    - mountPath: /host/opt/cni/bin
      name: cnibin
    - mountPath: /host/etc/os-release
      name: os-release
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/cni/net.d
      type: ""
    name: system-cni-dir
  - hostPath:
      path: /var/run/multus/cni/net.d
      type: ""
    name: multus-cni-dir
  - hostPath:
      path: /var/lib/cni/bin
      type: ""
    name: cnibin
  - hostPath:
      path: /etc/os-release
      type: File
    name: os-release
  - configMap:
      defaultMode: 484
      name: cni-binary-copy-script
    name: cni-binary-copy
