apiVersion: v1
kind: Pod
metadata:
  name: pod-testpmd
  
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-downlink

spec:
  nodeSelector:
    kubernetes.io/hostname: fdp-4qwzb-worker-0
  # hostNetwork: true
  # hostPID: true
  # hostIPC: true
  containers:
  - name: samplepod
    command: ["sleep", "99999"]
    image:  quay.io/aasmith/testpmd:latest
#    image: dockerfranck/testpmd
    securityContext:
      privileged: true
    resources:
      requests:
        memory: 1000Mi
        hugepages-1Gi: 3Gi
        cpu: '1'
      limits:
        hugepages-1Gi: 3Gi
        cpu: '1'
        memory: 1000Mi
    volumeMounts:
      - mountPath: /dev/hugepages
        name: hugepage
        readOnly: False
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
