apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-kernelargs-manual
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
  - skew_tick=1
  - nohz=on
  - rcu_nocbs=2-9
  - tuned.non_isolcpus=00000003
  - intel_pstate=disable
  - nosoftlockup
  - tsc=nowatchdog
  - intel_iommu=on
  - iommu=pt
  - isolcpus=managed_irq,2-9
  - systemd.cpu_affinity=0,1
  - default_hugepagesz=1G
  - nmi_watchdog=0
  - audit=0
  - mce=off
  - processor.max_cstate=1
  - idle=poll
  - intel_idle.max_cstate=0
